---

- stat: path={{ frontend_baas }}/package.json
  register: project
  when: backend_as_a_service == true

- name: (BaaS) Ensure node_modules bind point exists in shared folder.
  file: "path={{ frontend_baas }}/node_modules state=directory"
  when: backend_as_a_service == true

- name: (BaaS) Mount node_modules from VM onto shared folder.
  shell: mount --bind {{ frontend_packages }} {{ frontend_baas }}/node_modules
  become: yes
  become_method: sudo
  when: backend_as_a_service == true

- name: (BaaS) A package.json will exist on the client.
  shell: npm init -y
  when: project.stat.exists is not defined or project.stat.exists == False and backend_as_a_service == true
  args:
    chdir: "{{ frontend_baas }}"
    creates: package.json

- name: (BaaS) NPM dependencies will be installed.
  shell: npm install
  when: backend_as_a_service == true
  args:
    chdir: "{{ frontend_baas }}"