---
- hosts: all
  sudo: no
  tasks:

    - name: Ensure Apache is installed with support for Python WSGI
      yum: name={{ item }} state=present
      with_items: [httpd, mod_wsgi]
      sudo: yes

    - name: Ensure pip is installed
      yum: name=python-pip state=present
      sudo: yes

    - name: Ensure Django is installed (via pip)
      pip: name=Django version=1.8 state=present
      sudo: yes

    - name: Ensure HTTP daemon is running
      service: name=httpd state=restarted enabled=yes
      sudo: yes