# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"
  config.vm.box_check_update = true
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|

    vb.gui = false
    vb.cpus = 1
    vb.memory = 1024

  end

  config.vm.provision "kickstart", type: "shell", privileged: false, path: "server/provision/setup.sh"

end
