# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "chef/centos-7.0"
  config.vm.box_check_update = true
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|

    vb.gui = false
    vb.cpus = 1
    vb.memory = 1024

  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL

    # (Ansible Playbook) Ensure python output is printed as execution occurs.
    # (Ansible Playbook) Specify what Ansible Playbook is running against.
    export PYTHONUNBUFFERED=1

    INVENTORY=$(mktemp -t XXXXX.hosts)
    echo 127.0.0.1 > $INVENTORY

    # Ensure Ansible is installed.
    sudo yum install -y epel-release
    sudo yum install -y ansible

    # Run Ansible provisioner.
    ansible-playbook /vagrant/server/provision/ansible.yml --connection=local -i $INVENTORY -u vagrant

    # Clean up
    rm $INVENTORY

  SHELL

end
