---

- name: Apache and Python WSGI will be present.
  yum: name={{ item }} state=present
  with_items: [httpd, mod_wsgi]
  become: yes
  become_method: sudo

- name: VirtualHost will be configured for coupling of client and server.
  copy: src=virtualhost.conf dest=/etc/httpd/conf.d/virtualhost.conf
  become: yes
  become_method: sudo
  when: backend_as_a_service == false

- name: VirtualHost will be configured for separation of client and server.
  copy: src=virtualhost_baas.conf dest=/etc/httpd/conf.d/virtualhost.conf
  become: yes
  become_method: sudo
  when: backend_as_a_service == true

- name: Add the Apache user to the vagrant users group.
  command: usermod -a -G vagrant apache
  become: yes
  become_method: sudo

- name: Give Apache execute permissions for VirtualEnv.
  command: chmod 710 /home/vagrant