---

- hosts: all
  remote_user: vagrant
  roles:
    - apache
    - django
    - django_init
  tasks:

    - stat: path=/vagrant/backend/requirements.txt
      register: reqs

    - name: A project requirements file will exist.
      command: cp /vagrant/server/provision/roles/django/files/requirements.txt /vagrant/backend/requirements.txt
      when: reqs.stat.exists is not defined or reqs.stat.exists == False

    - name: Project requirements will be installed.
      pip: requirements=/vagrant/backend/requirements.txt
      become: yes
      become_method: sudo
      notify:
        - Restart Server