---

- hosts: all
  remote_user: vagrant
  roles:
    - apache
    - django
  tasks:
    - stat: path=/vagrant/backend/manage.py
      register: project

    - stat: path=/vagrant/backend/requirements.txt
      register: reqs

    - name: A project will exist.
      command: django-admin.py startproject project . chdir=/vagrant/backend
      when: project.stat.exists is not defined or project.stat.exists == False

    - name: A project requirements file will exist.
      command: cp /vagrant/server/provision/roles/django/files/requirements.txt /vagrant/backend/requirements.txt
      when: reqs.stat.exists is not defined or reqs.stat.exists == False

    - name: Project requirements will be installed.
      pip: requirements=/vagrant/backend/requirements.txt
      become: yes
      become_method: sudo
      notify:
        - Restart Server