---

- hosts: all
  remote_user: vagrant

  pre_tasks:

    - stat: path=/vagrant/backend/manage.py
      register: project

    - stat: path=/vagrant/backend/requirements.txt
      register: reqs

  roles:

    - apache
    - django
    - { role: django_init, when: project.stat.exists is not defined or project.stat.exists == False }

  tasks:

    - name: A project requirements file will exist.
      command: cp /vagrant/server/provision/roles/django/files/requirements.txt /vagrant/backend/requirements.txt
      when: reqs.stat.exists is not defined or reqs.stat.exists == False

    - name: Project requirements will be installed.
      pip: requirements=/vagrant/backend/requirements.txt
      become: yes
      become_method: sudo

    - name: Project schema will be applied to the database engine.
      command: python manage.py migrate chdir=/vagrant/backend

  post_tasks:

    - command: echo 'Good to go!'
      notify:
        - Restart Server