---

- stat: path={{ backend }}/manage.py
  register: project

- stat: path={{ backend }}/requirements.txt
  register: project_requirements

- name: A project will exist.
  shell: . {{ backend_env }}/bin/activate && django-admin.py startproject app . chdir={{ backend }}
  when: project.stat.exists is not defined or project.stat.exists == False

- name: A project requirements file will exist.
  shell: . {{ backend_env }}/bin/activate && pip freeze > requirements.txt chdir={{ backend }}
  when: project_requirements.stat.exists is not defined or project_requirements.stat.exists == False

- name: Project requirements shall be installed.
  pip: requirements={{ backend }}/requirements.txt virtualenv={{ backend_env }}

- name: Project schema shall be applied to database engine.
  shell: . {{ backend_env }}/bin/activate && python manage.py migrate chdir={{ backend }}

- name: Ensure STATIC_URL points to server assets correctly when client and server are coupled.
  script: set_settings_variable.sh -d {{ backend }}/app -k "STATIC_URL" -v "\"'\/static\/'\""
  when: backend_as_a_service == false

- name: Ensure STATIC_URL points to server assets correctly when client and server are separated.
  script: set_settings_variable.sh -d {{ backend }}/app -k "STATIC_URL" -v "\"'\/static\/backend\/'\""
  when: backend_as_a_service == true

- name: Ensure STATIC_ROOT is set in project settings.
  script: set_settings_variable.sh -d {{ backend }}/app -k "STATIC_ROOT" -v "\"os.path.join(BASE_DIR, 'static')\""

- name: Project static files will be collected.
  shell: . {{ backend_env }}/bin/activate && python manage.py collectstatic --noinput chdir={{ backend }}