---

- hosts: all
  remote_user: vagrant

  vars_files:
    - settings.yml

  roles:

    - apache-server
    - django-framework
    # Uncomment to enable installation of NPM.
    # - npm-packagemanager
    - django-app
    # Uncomment to enable package.json and NPM install (BaaS only).
    # - npm-frontend

  post_tasks:

    - name: Provisioning has completed!
      shell: "true"
      notify:
        - Restart Server