---

- hosts: all
  remote_user: vagrant

  vars_files:
    - settings.yml

  roles:

    - apache-server
    - django-framework
    # Uncomment to enable installation of NPM.
    # - npm-packagemanager
    - django-app
    # Uncomment to enable package.json and NPM install (BaaS only).
    # - npm-frontend

  tasks:

    - name: Nearly done!
      shell: echo 'Placeholder for some closing notes'
      notify:
        - Restart Server