---

- hosts: all
  remote_user: vagrant

  roles:

    - apache-server
    - django-app
    - django-app_init

  tasks:

    - name: Nearly done!
      shell: echo 'Placeholder for some closing notes'
      notify:
        - Restart Server