---

- hosts: all
  roles:
    - apache
    - django
  tasks:
    - stat: path=/vagrant/backend/manage.py
      register: project

    - name: A project will exist.
      command: django-admin.py startproject project . chdir=/vagrant/backend
      notify:
        - Restart Server
      when: project.stat.exists is not defined or project.stat.exists == False