---

- hosts: all
  remote_user: vagrant

  vars_files:
    - settings.yml

  roles:

    - apache-server
    - django-framework
    - django-app

  tasks:

    - name: Nearly done!
      shell: echo 'Placeholder for some closing notes'
      notify:
        - Restart Server